// packages-front/react-vite/src/pages/product.tsx
import { useEffect, useState } from 'react';
import { Table } from 'antd';
import type { TableProps } from 'antd';
import request from '../request';

interface DataType {
  name: string;
}

const columns: TableProps<DataType>['columns'] = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
];

export default function Product() {
  const [data, setData] = useState([]);

  useEffect(() => {
    request('/v1/product').then((res) => {
      setData(res.data);
    });
  }, []);

  return <Table columns={columns} dataSource={data} rowKey="id" />;
}

// packages-front/vue/src/views/product.vue
<template>
  <a-table :dataSource="tableData" :columns="columns">
    <template #headerCell="{ column }">
      <template v-if="column.key === 'name'">
        <span> Name </span>
      </template>
    </template>
  </a-table>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import request from '../request'

const tableData = ref([])

onMounted(async () => {
  await request('/v1/product').then((res) => {
    tableData.value = res.data
  })
})

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name'
  }
]
</script>

<script lang="ts">
export default {
  name: 'product-view'
}
</script>
